# Generated by Django 2.0 on 2018-01-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
