# Generated by Django 2.0 on 2018-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0002_auto_20180106_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
