# Generated by Django 2.0 on 2018-01-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0003_auto_20180107_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
