# Generated by Django 2.0 on 2018-01-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0004_auto_20180107_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='kname',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
